BeMyGuest/Models/Host.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BeMyGuest.Models
{
    public class Host
    {
        public Host()
        {
            this.JoinEntries = new HashSet<Gathering>();
        }
        public int HostId { get; set; }
        [Display(Name = "Host Name")]
        public string HostName { get; set; }
        [Display(Name = "Host Email")]
        public string HostEmail { get; set; }
        public virtual ApplicationUser User { get; set; }
        public virtual ICollection<Gathering> JoinEntries { get; set; }
    }
}

BeMyGuest/Controllers/GuestsController.cs
using BeMyGuest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BeMyGuestMVC.Controllers
{
    // [Authorize(Roles = "Admin")]
    [Authorize(Roles = "Guest")]
    [Authorize(Roles = "Host")]
    public class GuestsController : Controller
    {
        private readonly BeMyGuestContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public GuestsController(UserManager<ApplicationUser> userManager, BeMyGuestContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        // show only this users guests
        public ActionResult Index()
        {
            List<Guest> model = _db.Guests.ToList();
            model.Sort((x, y) => string.Compare(x.Name, y.Name));
            return View(model);
        }
        [Authorize(Roles="Host")]
        public ActionResult Create() //--> stretch for creating their own event
        {
            ViewBag.GuestId = new SelectList(_db.Guests, "GuestId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Guest guest)
        {
            _db.Guests.Add(guest);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id) //needs to connect to Host, GatheringJoin, CovidData
        {
            var thisGuest = _db.Guests
                // .Include(guest => guest.Hosts)
                // .ThenInclude(join => join.Host)
                .FirstOrDefault(guest => guest.GuestId == id);
            return View(thisGuest);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            // Guest.User = currentUser;
            var thisGuest = _db.Guests.FirstOrDefault(guests => guests.GuestId == id);
            if (thisGuest == null)
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(thisGuest);
        }

        [HttpPost]
        public ActionResult Edit(Guest guest)
        {
            _db.Entry(guest).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = guest.GuestId });
        }

        public ActionResult Delete(int id)
        {
            var thisGuest = _db.Guests
                // .Include(guest => guest.Hosts)
                // .ThenInclude(join => join.Host)
                // // .Include(guest => guest.CovidData) // not sure how to properly set this up, or if it's needed
                .FirstOrDefault(guest => guest.GuestId == id);
            if (thisGuest == null)
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(thisGuest);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)//, int joinId)
        {
            // if (joinId != 0)
            // {
            //     var joinEntry = _db.Gathering.FirstOrDefault(entry => entry.GuestId == id);
            //     if(joinEntry != null)
            //     {
            //         _db.Gathering.Remove(joinEntry);
            //         var thisGuest = _db.Guests
            //             // .Include(guest => guest.Hosts)
            //             // .ThenInclude(join => join.Host)
            //             // .Include(guest => guest.CovidData) // not sure how to properly set this up or if needed
            //             .FirstOrDefault(guests => guests.GuestId == id);
            //         _db.Guests.Remove(thisGuest);
            //         _db.SaveChanges();
            //     }
            // }
            // else
            // {
            var thisGuest = _db.Guests
                // .Include(guest => guest.Hosts)
                // .ThenInclude(join => join.Host)
                // .Include(guest => guest.CovidData)
                .FirstOrDefault(guests => guests.GuestId == id);
            _db.Guests.Remove(thisGuest);
            _db.SaveChanges();
            // }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteHost(int joinId, int GuestId)
        {
            var joinEntry = _db.Gathering.FirstOrDefault(entry => entry.GatheringId == joinId);
            _db.Gathering.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = GuestId });
        }
    }
}

BeMyGuest/Controllers/HostsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Collections.Generic;
using System.Linq;
using BeMyGuest.Models;

namespace BeMyGuest.Controllers
{
    // [Authorize(Roles = "Admin")]
    [Authorize(Roles = "Host")]
    public class HostsController : Controller
    {
        private readonly BeMyGuestContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public HostsController(UserManager<ApplicationUser> userManager, BeMyGuestContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        public ActionResult Index()
        {
            Dictionary<object, object> model = new Dictionary<object, object>();
            List<Guest> guests = _db.Guests.ToList();
            guests.Sort((x, y) => string.Compare(x.Name, y.Name));
            List<Event> events = _db.Events.ToList();
            events.Sort((x, y) => string.Compare(x.EventTitle, y.EventTitle));
            model.Add("guests", guests);
            model.Add("events", events);
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Host host)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            host.User = currentUser;
            _db.Hosts.Add(host);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            var thisHost = _db.Hosts.FirstOrDefault(host => host.HostId == id);
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            ViewBag.IsCurrentUser = userId != null ? userId == thisHost.User.Id : false;
            return View(thisHost);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            var thisHost = _db.Hosts
                .Where(entry => entry.User.Id == currentUser.Id)
                .FirstOrDefault(host => host.HostId == id);
            if (thisHost == null)
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(thisHost);
        }

        [HttpPost]
        public ActionResult Edit(Host host)
        {
            _db.Entry(host).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> AddGuest(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            Host thisHost = _db.Hosts
                .Where(entry => entry.User.Id == currentUser.Id)
                .FirstOrDefault(host => host.HostId == id);
            if (thisHost == null)
            {
                return RedirectToAction("Details", new { id = id });
            }
            ViewBag.GuestId = new SelectList(_db.Guests);
            return View(thisHost);
        }

        [HttpPost]
        public ActionResult AddGuest(Host host, int GuestId)
        {
            if (GuestId != 0)
            {
                var returnedJoined = _db.Gathering.Any(join => join.HostId == host.HostId && join.GuestId == GuestId);
                if (!returnedJoined)
                {
                    _db.Gathering.Add(new Gathering() { GuestId = GuestId, HostId = host.HostId });
                }
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> AddEvent(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            Host thisHost = _db.Hosts
                .Where(entry => entry.User.Id == currentUser.Id)
                .FirstOrDefault(host => host.HostId == id);
            if (thisHost == null)
            {
                return RedirectToAction("Details", new { id = id });
            }
            ViewBag.EventId = new SelectList(_db.Events);
            return View(thisHost);
        }

        [HttpPost]
        public ActionResult AddEvent(Host host, int EventId)
        {
            if (EventId != 0)
            {
                var returnedJoined = _db.Gathering.Any(join => join.HostId == host.HostId && join.EventId == EventId);
                if (!returnedJoined)
                {
                    _db.Gathering.Add(new Gathering() { EventId = EventId, HostId = host.HostId });
                }
            }
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            Host thisHost = _db.Hosts
                .Where(entry => entry.User.Id == currentUser.Id)
                .FirstOrDefault(host => host.HostId == id);
            if (thisHost == null)
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(thisHost);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisHost = _db.Hosts.FirstOrDefault(host => host.HostId == id);
            _db.Hosts.Remove(thisHost);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteGuest(int joinId)
        {
            var joinEntry = _db.Gathering.FirstOrDefault(entry => entry.GatheringId == joinId);
            _db.Gathering.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BeMyGuest/Views/Hosts/AddEvent.cshtml
@* @{
    Layout = "_Layout";
}

@model BeMyGuest.Models.Host


<h1>Add Event</h1>
@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.HostId)
    <h4>Event Title: @Html.TextBoxFor(model => model.EventTitle)</h4>

    <input type="submit" value="Add Event" class="btn btn-default" />
} *@

BeMyGuest/Views/Hosts/Create.cshtml
@{
    Layout = "_Layout";
}

@model BeMyGuest.Models.Host

<h2>Add a New Host</h2>
<hr />
<div class="card" style="width: 36rem;">
    <div class="card-body">
        @using (Html.BeginForm())
        {
            <div class="form-group">
                @Html.LabelFor(model => model.HostName)
                @Html.TextBoxFor(model => model.HostName)
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.HostEmail)
                @Html.TextBoxFor(model => model.HostEmail)
            </div>
            <div class="form-group">
                <input type="submit" value="Add New Host" class="btn btn-outline-info"/>
            </div>
        }
    </div>
</div>

<h3>@Html.ActionLink("Hosts Home", "Index")</h3>

BeMyGuest/Views/Hosts/Delete.cshtml
@{
    Layout ="_Layout";
}

@model BeMyGuest.Models.Host

<h2>Delete Host</h2>
<hr />
<h4>Are you sure you want to delete this host?</h4>

<div class="card mx-auto" style="width: 36rem;">
    <div class="card-body">
        <div class="form-group row">
            @Html.DisplayNameFor(model => model.HostName): @Html.DisplayFor(model => model.HostName)
            @using (Html.BeginForm())
            {
                <input type="submit" value="Delete" class="btn btn warning" />
            }
        </div>
    </div>
</div>

<h3>@Html.ActionLink("Back to Host Details", "Details", new {id = Model.HostId}) || @Html.ActionLink("Back to Hosts", "Index")</h3>

BeMyGuest/Views/Hosts/Details.cshtml
@{
    Layout = "_Layout";
}

@model BeMyGuest.Models.Host

<h2>Host Details</h2>
<hr />

<div class="card" style="width: 36rem;">
    <div class="card-body">
        <h3>@Html.DisplayNameFor(model => model.HostName):</h3>
        <h4>@Html.DisplayFor(model => model.HostName)</h4>
        <h3>@Html.DisplayNameFor(model => model.HostEmail):</h3>
        <h4>@Html.DisplayFor(model => model.HostEmail)</h4>
    </div>
</div>

@* @if(@Model.Guests.Count == 0)
{
    <p>This event does not have any guests yet.</p>
    <hr />
}
else
{
    <h3>Guest List:</h3>
    <ul>
        @foreach(var join in Model.Guests)
        {
            <div class="form-group">
                <li><h4>@join.Guest.GuestName</h4></li>
            </div>
            @using (Html.BeginForm("DeleteJoin", "Guests"))
            {
                <div class="form-group">
                    @Html.Hidden("joinId", @join.GatheringId)
                    <input type="submit" value="Remove Guest" class="btn btn-default"/>
                </div>
            }
        }
    </ul>
} *@


@if (User.Identity.IsAuthenticated && ViewBag.IsCurrentUser)
{
    <h3>@Html.ActionLink("Host Home", "Index") || @Html.ActionLink("Edit Host", "Edit", new { id = Model.HostId }) || @Html.ActionLink("Delete Host", "Delete", new { id = Model.HostId }) || @Html.ActionLink("Create an Event", "AddEvent", new { id = Model.HostId})</h3>
}
else
{
    <h3>@Html.ActionLink("Host Home", "Index")</h3>
}

BeMyGuest/Views/Hosts/Edit.cshtml
@{
    Layout = "_Layout";
}

@model BeMyGuest.Models.Host

<h2>Edit</h2>
<hr />
<h4>Edit this Host: @Html.DisplayFor(model => model.HostName)</h4>

@using (Html.BeginForm())
{
    <div class="card" style="width: 48rem;">
        <div class="card-body">
            @Html.HiddenFor(model => model.HostId)
            <div class="form-group row">
                @Html.LabelFor(model => model.HostName, new { @class="col-sm-3 col-form-label" })
                @Html.EditorFor(model => model.HostName, new { @class="col-sm-8 col-form-label" })
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.HostEmail, new { @class="col-sm-3 col-form-label" })
                @Html.EditorFor(model => model.HostEmail, new { @class="col-sm-8 col-form-label" })
            </div>
            <div class="form-group row">
                <input type="submit" value="Save" class="btn btn-outline-info">
            </div>
        </div>
    </div>
}

<h3>@Html.ActionLink("Hosts Home", "Index", "Hosts")</h3>

BeMyGuest/Views/Hosts/Index.cshtml
@{
    Layout = "_Layout";
}

@using BeMyGuest.Models

<h2>Host Home</h2>
<hr>

<div class="card" style="width: 36rem;">
    <div class="card-body">
        <h3>@Html.ActionLink("Back to Home", "Index", "Home") || @Html.ActionLink("Create an Event", "Index", "Event") || @Html.ActionLink("Add a co-host", "Create", "Hosts")</h3>
    </div>
</div>