BeMyGuest/Models/Guest.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System;

namespace BeMyGuest.Models
{
    public class Guest
    {
        public Guest()
        {
            this.JoinEntries = new HashSet<Gathering>();
        }

        // Guest Info
        public int GuestId { get; set; }
        public string Name { get; set; }
        public string Pronouns { get; set; }
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        // public string Phone { get; set; } // Stretch for instant contact tracing

        // Covid Screening & Medical Requirements
        public bool Vaccinated { get; set; } = false;
        [Display(Name = "High Risk")]
        public bool HighRisk { get; set; } = false;
        [Display(Name = "Recent Travel")]
        public bool RecentTravel { get; set; } = false;
        [Display(Name = "Completed the Questionnaire")]
        public bool CompletedQuestionnaire { get; set; } = false;
        [Display(Name = "Medical Mobility Needs")]
        public string MedicalMobilityNeeds { get; set; }
        [Display(Name = "Medical Conditions")]
        public string MedicalConditions { get; set; }
        [Display(Name = "Service Animal")]
        public bool ServiceAnimal { get; set; } = true;

        // Food, Drink, & Misc.
        [Display(Name = "Dietary Restrictions")]
        public string DietaryRestrictions { get; set; }
        public string Allergies { get; set; }
        [Display(Name = "Preferred Language")]
        public string PreferredLanguage { get; set; }
        [Display(Name = "Alcohol Free")]
        public bool AlcoholFree { get; set; } = false;
        [Display(Name = "Not-a-Hugger")]
        public bool NotAHugger { get; set; } = false;

        // Group Connections
        [Display(Name = "Plus One(s) in Tow")]
        public bool PlusOne { get; set; } = false;
        [Display(Name = "Small Children in Tow")]
        public bool SmallChildren { get; set; } = false;
        //public virtual ICollection <Pod> PodMates { get; set; } // stretch

        //Outside Table Data
        public virtual ApplicationUser User { get; set; }
        public virtual ICollection<Gathering> JoinEntries { get; set; }
        public int? EvidenceId { get; set; }
        public virtual Evidence Evidence { get; set; }
    }
}

BeMyGuest/Controllers/EventController.cs
using BeMyGuest.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;
using System.Security.Claims;
using System.Collections.Generic;
using System.Linq;


namespace BeMyGuest.Controllers
{
    public class EventsController : Controller
    {
        private readonly BeMyGuestContext _db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;
        public EventsController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager, BeMyGuestContext db)
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _db = db;
        }

        public async Task<ActionResult> Index()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            var userEvents = _db.Events.Where(entry => entry.User.Id == currentUser.Id).ToList();
            return View(userEvents);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(Event myEvent)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            myEvent.User = currentUser;
            _db.Events.Add(myEvent);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Details(int id)
        {
            var thisEvent = _db.Events.FirstOrDefault(myEvent => myEvent.EventId == id);
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            ViewBag.IsCurrentUser = userId != null? userId == thisEvent.User.Id : false;
            return View(thisEvent);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            var thisEvent = _db.Events.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(myEvent => myEvent.EventId == id);
            if(thisEvent == null)
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(thisEvent);
        }

        [HttpPost]
        public ActionResult Edit(Event myEvent)
        {
            _db.Entry(myEvent).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = myEvent.EventId});
        }

        public async Task<ActionResult> AddGuest(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            var thisEvent = _db.Events.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(myEvent => myEvent.EventId == id);
            if(thisEvent == null)
            {
                return RedirectToAction("Details", new { id = id});
            }
            ViewBag.GuestId = new SelectList(_db.Guests, "GuestId", "Type");
            return View(thisEvent);
        }

        [HttpPost]
        public ActionResult AddGuest(Event myEvent, int GuestId)
        {
            if(GuestId != 0)
            {
                var returnedJoin = _db.Gathering
                    .Any(join => join.GuestId == GuestId && join.EventId == myEvent.EventId);
                    if(!returnedJoin)
                    {
                        _db.Gathering.Add(new Gathering() { EventId = myEvent.EventId, GuestId = GuestId});
                    }
            }
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = myEvent.EventId});
        }

        public async Task<ActionResult> AddHost(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            var thisEvent = _db.Events.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(myEvent => myEvent.EventId == id);
            if(thisEvent == null)
            {
                return RedirectToAction("Details", new { id = id});
            }
            ViewBag.HostId = new SelectList(_db.Hosts, "HostId", "Type");
            return View(thisEvent);
        }

        [HttpPost]
        public ActionResult AddHost(Event myEvent, int HostId)
        {
            if(HostId != 0)
            {
                var returnedJoin = _db.Gathering
                    .Any(join => join.HostId == HostId && join.EventId == myEvent.EventId);
                    if(!returnedJoin)
                    {
                        _db.Gathering.Add(new Gathering() { EventId = myEvent.EventId, HostId = HostId});
                    }
            }
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = myEvent.EventId});
        }

        public async Task<ActionResult> Delete(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            var thisEvent = _db.Events.Where(entry => entry.User.Id == currentUser.Id).FirstOrDefault(myEvents => myEvents.EventId == id);
            if(thisEvent == null)
            {
                return RedirectToAction("Details", new { id = id});
            }
            return View(thisEvent);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisEvent = _db.Events.FirstOrDefault(myEvents => myEvents.EventId == id);
            _db.Events.Remove(thisEvent);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteGuest(int joinId)
        {
            var joinEntry = _db.Gathering.FirstOrDefault(entry => entry.GatheringId == joinId);
            _db.Gathering.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteHost(int joinId)
        {
            var joinEntry = _db.Gathering.FirstOrDefault(entry => entry.GatheringId == joinId);
            _db.Gathering.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

BeMyGuest/Controllers/GuestsController.cs
using BeMyGuest.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace BeMyGuestMVC.Controllers
{
    // [Authorize(Roles = "Admin")]
    [Authorize(Roles = "Guest")]
    [Authorize(Roles = "Host")]
    public class GuestsController : Controller
    {
        private readonly BeMyGuestContext _db;
        private readonly UserManager<ApplicationUser> _userManager;

        public GuestsController(UserManager<ApplicationUser> userManager, BeMyGuestContext db)
        {
            _userManager = userManager;
            _db = db;
        }

        // show only this users guests
        public ActionResult Index()
        {
            List<Guest> model = _db.Guests.ToList();
            model.Sort((x, y) => string.Compare(x.Name, y.Name));
            return View(model);
        }
        [Authorize(Roles="Host")]
        public ActionResult Create() //--> stretch for creating their own event
        {
            ViewBag.GuestId = new SelectList(_db.Guests, "GuestId", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Guest guest)
        {
            _db.Guests.Add(guest);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id) //needs to connect to Host, GatheringJoin, CovidData
        {
            var thisGuest = _db.Guests
                // .Include(guest => guest.Hosts)
                // .ThenInclude(join => join.Host)
                .FirstOrDefault(guest => guest.GuestId == id);
            return View(thisGuest);
        }

        public async Task<ActionResult> Edit(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
            var currentUser = await _userManager.FindByIdAsync(userId);
            // Guest.User = currentUser;
            var thisGuest = _db.Guests.FirstOrDefault(guests => guests.GuestId == id);
            if (thisGuest == null)
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(thisGuest);
        }

        [HttpPost]
        public ActionResult Edit(Guest guest)
        {
            _db.Entry(guest).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = guest.GuestId });
        }

        public ActionResult Delete(int id)
        {
            var thisGuest = _db.Guests
                // .Include(guest => guest.Hosts)
                // .ThenInclude(join => join.Host)
                // // .Include(guest => guest.CovidData) // not sure how to properly set this up, or if it's needed
                .FirstOrDefault(guest => guest.GuestId == id);
            if (thisGuest == null)
            {
                return RedirectToAction("Details", new { id = id });
            }
            return View(thisGuest);
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)//, int joinId)
        {
            // if (joinId != 0)
            // {
            //     var joinEntry = _db.Gathering.FirstOrDefault(entry => entry.GuestId == id);
            //     if(joinEntry != null)
            //     {
            //         _db.Gathering.Remove(joinEntry);
            //         var thisGuest = _db.Guests
            //             // .Include(guest => guest.Hosts)
            //             // .ThenInclude(join => join.Host)
            //             // .Include(guest => guest.CovidData) // not sure how to properly set this up or if needed
            //             .FirstOrDefault(guests => guests.GuestId == id);
            //         _db.Guests.Remove(thisGuest);
            //         _db.SaveChanges();
            //     }
            // }
            // else
            // {
            var thisGuest = _db.Guests
                // .Include(guest => guest.Hosts)
                // .ThenInclude(join => join.Host)
                // .Include(guest => guest.CovidData)
                .FirstOrDefault(guests => guests.GuestId == id);
            _db.Guests.Remove(thisGuest);
            _db.SaveChanges();
            // }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteHost(int joinId, int GuestId)
        {
            var joinEntry = _db.Gathering.FirstOrDefault(entry => entry.GatheringId == joinId);
            _db.Gathering.Remove(joinEntry);
            _db.SaveChanges();
            return RedirectToAction("Details", new { id = GuestId });
        }
    }
}

BeMyGuest/Views/Guests/Create.cshtml
@{
    Layout = "_Layout";
}

@model BeMyGuest.Models.Guest

<h2>Add a New Guest</h2>
<hr />
@using (Html.BeginForm())
{
    <div class="card mx-auto" style="width: 48rem;">
        <div class="card-body">
            <div class="form-group row">

                @* @Hidden.For("CovidDataId") *@

                @Html.LabelFor(model => model.Name, new { @class="col-sm-3 col-form-label" })
                @Html.TextBoxFor(model => model.Name, new { @class="col-sm-8", @placeholder="e.g. Janey Smith"})
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Email, new { @class="col-sm-3 col-form-label" })
                @Html.TextBoxFor(model => model.Email, new { @class="col-sm-8 col-form-label", @placeholder ="janey@example.com"  })
            </div>
            <div class="form-group row">
                <input type="submit" value="Add New Guest" class="btn btn-outline-info"/>
            </div>
        </div>
    </div>
}

<h3>@Html.ActionLink("Show all guests", "Index")</h3>

BeMyGuest/Views/Guests/Delete.cshtml
@{
    Layout ="_Layout";
}

@model BeMyGuest.Models.Guest

<h2>Delete Guest</h2>
<hr />
<h4>Are you sure you want to delete this guest?</h4>
<div class="card mx-auto" style="width: 36rem;">
    <div class="card-body">
        <div class="form-group row">
            @Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
            @using (Html.BeginForm())
            {
                <input type="submit" value="Delete" class="btn btn warning" />
            }
        </div>
    </div>
</div>

<h3>@Html.ActionLink("Back to Guest Details", "Details", new {id = Model.GuestId}) || @Html.ActionLink("Back to Guests", "Index")</h3>

BeMyGuest/Views/Guests/Details.cshtml
@{
    Layout = "_Layout";
}

@model BeMyGuest.Models.Guest

<h2 style="text-align:center">Guest Details</h2>
<hr />

<div class="card" style="width: 48rem;">
    <div class="card-body">
        <h3 class="card-title">@Html.DisplayNameFor(model => model.Name):</h3>
        <h4>@Html.DisplayFor(model => model.Name)</h4>

        <ul class="card-text" style="list-style: none;">
            <li class="form-group row">@Html.DisplayNameFor(model => model.Pronouns): @Html.DisplayFor(model => model.Pronouns)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.Email): @Html.DisplayFor(model => model.Email)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.Vaccinated): @Html.DisplayFor(model => model.Vaccinated)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.HighRisk): @Html.DisplayFor(model => model.HighRisk)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.RecentTravel): @Html.DisplayFor(model => model.RecentTravel)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.CompletedQuestionnaire): @Html.DisplayFor(model => model.CompletedQuestionnaire)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.MedicalMobilityNeeds): @Html.DisplayFor(model => model.MedicalMobilityNeeds)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.MedicalConditions): @Html.DisplayFor(model => model.MedicalConditions)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.ServiceAnimal): @Html.DisplayFor(model => model.ServiceAnimal)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.DietaryRestrictions): @Html.DisplayFor(model => model.DietaryRestrictions)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.Allergies): @Html.DisplayFor(model => model.Allergies)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.PreferredLanguage): @Html.DisplayFor(model => model.PreferredLanguage)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.AlcoholFree): @Html.DisplayFor(model => model.AlcoholFree)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.NotAHugger): @Html.DisplayFor(model => model.NotAHugger)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.PlusOne): @Html.DisplayFor(model => model.PlusOne)</li>
            <li class="form-group row">@Html.DisplayNameFor(model => model.SmallChildren): @Html.DisplayFor(model => model.SmallChildren)</li>
        </ul>
            <h3>Send Invite</h3>
            <h3><a href="mailto:@Model.Email?subject=You're Invited!&body=You have been invited to a gathering by (name here)! Here are the event details: (event details such as date, time, place, etc.). Please click the link below and use this code 'RFDJ123' to RSVP and answer the 'social cues' needed to make this gathering awesome. If you haven't created an account with BeMyGuest, you will need to create one and register as a guest." class="btn btn-outline-info">Send Invite</a></h3>
    </div>
</div>
<br>
<br>

@* @if(@Model.CovidDataSet.Count == 0)
{
    <p>This guest has not filled out their questionnaire yet.</p>
<h3>@Html.DisplayNameFor(model => model.Name):</h3>
<h4>@Html.DisplayFor(model => model.Name)</h4>
<h5>Pronouns: They/Them</h5>
<h5>Vaccinated: Yes</h5>
<h5>Recent Travel: No</h5>
<h5>COVID Questionnaire: Completed</h5>
<h5>Medical Mobility Needs: None</h5>
<h5>Medical Conditions: Epilepsy</h5>
<h5>Service Animal: Yes</h5>
<h6>Instructions: Please do not pet dog</h6>
<h5>Dietary Restrictions: Vegan</h5>
<h5>Allergies: Shellfish</h5>
<h5>Preferred Lanuage: Russian</h5>
<h5>Alcohol-Friendly</h5>
<h5>Physical Contact: Not a hugger</h5>
<h5>Plus 1: No</h5>
<h5>Small Children in Tow: No</h5>



@* @if(@Model.Hosts.Count == 0)
    {
    <p>This event does not have any guests yet.</p>
    <hr />
    }
    else
    {
    <h3>Guest List:</h3>
    <ul>
        @foreach(var join in Model.Host)
        {
            <div class="form-group">
                <li><h4>@join.Event.EventName</h4></li>
            </div>
            @using (Html.BeginForm("DeleteJoin", "Events"))
            {
                <div class="form-group">
                    @Html.Hidden("joinId", @join.GatheringId)
                    <input type="submit" value="Remove From Event" class="btn btn-default"/>
                </div>
            }
        }
    </ul>
} *@
@* @if (User.Identity.IsAuthenticated && ViewBag.IsCurrentUser)
{ *@
<h3>@Html.ActionLink("Edit Guest", "Edit", new { id = Model.GuestId }, new {@class="btn btn-outline-info"}) || @Html.ActionLink("Add a Guest", "AddGuest", new { id = Model.GuestId }, new {@class ="btn btn-outline-info"}) || @Html.ActionLink("Delete Guest", "Delete", new { id = Model.GuestId }, new {@class ="btn btn-outline-info"}) || @Html.ActionLink("Guests Home", "Index", new {@class ="btn btn-outline-info"})</h3>

BeMyGuest/Views/Guests/Edit.cshtml
@{
    Layout = "_Layout";
}

@model BeMyGuest.Models.Guest

<h2>Social Q's Questionnaire: @Html.DisplayFor(model => model.Name)</h2>
<hr />

@using (Html.BeginForm())
{
    <div class="card mx-auto" style="width: 48rem;">
        <div class="card-body">
            @Html.HiddenFor(model => model.GuestId)
            <div class="form-group row">
                @Html.LabelFor(model => model.Name, new { @class="col-sm-3 col-form-label" })
                @Html.TextBoxFor(model => model.Name, new { @class="col-sm-8 col-form-label" })
            </div>
            <div class="form-group row">
                @Html.LabelFor(model => model.Email, new { @class="col-sm-3 col-form-label" })
                @Html.TextBoxFor(model => model.Email, new { @class="col-sm-8 col-form-label", @placeholder ="janey@example.com" })
            </div>
    @* <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name)
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Email)
        @Html.TextBoxFor(model => model.Email)
    </div> *@
    <div class="form-group row">
        @Html.Label("What are your pronouns?")
        @Html.TextBoxFor(model => model.Pronouns)
    </div>
    <div class="form-group row">
        @Html.Label("Have you been vaccinated?")
        @Html.TextBoxFor(model => model.Vaccinated)
    </div>
    <div class="form-group row">
        @Html.Label("Are you apart of a high-risk group?")
        @Html.TextBoxFor(model => model.HighRisk)
    </div>
    <div class="form-group row">
        @Html.Label("Have you traveled outside of your state in the past two weeks?")
        @Html.TextBoxFor(model => model.RecentTravel)
    </div>
    <div class="form-group row">
        @Html.Label("Have you completed the COVID Questionnaire?")
        @Html.TextBoxFor(model => model.CompletedQuestionnaire)
    </div>
    <div class="form-group row">
        @Html.Label("Do you have any medical mobility needs?")
        @Html.TextBoxFor(model => model.MedicalMobilityNeeds)
    </div>
    <div class="form-group row">
        @Html.Label("Any medical conditions you would like other to be aware of?")
        @Html.TextBoxFor(model => model.MedicalConditions)
    </div>
    <div class="form-group row">
        @Html.Label("Do you require the aid of a service animal?")
        @Html.TextBoxFor(model => model.ServiceAnimal)
    </div>
    <div class="form-group row">
        @Html.Label("Do you have any dietary restrictions?")
        @Html.TextBoxFor(model => model.DietaryRestrictions)
    </div>
    <div class="form-group row">
        @Html.Label("Any food allergies?")
        @Html.TextBoxFor(model => model.Allergies)
    </div>
    <div class="form-group row">
        @Html.Label("What is your preferred language?")
        @Html.TextBoxFor(model => model.PreferredLanguage)
    </div>
    <div class="form-group row">
        @Html.Label("Do you imbibe or are you alcohol free?")
        @Html.TextBoxFor(model => model.AlcoholFree)
    </div>
    <div class="form-group row">
        @Html.Label("Do you accept hugs?")
        @Html.TextBoxFor(model => model.NotAHugger)
    </div>
    <div class="form-group row">
        @Html.Label("Plus one?")
        @Html.TextBoxFor(model => model.PlusOne)
    </div>
    <div class="form-group row">
        @Html.Label("Any small children attending with you?")
        @Html.TextBoxFor(model => model.SmallChildren)
    </div>
        <div class="form-group row">
            <input type="submit" value="Save" class="btn btn-outline-info">
        </div>
    </div>
    </div>
}

<h3>@Html.ActionLink("Show all guests", "Index", "Guests")</h3>

BeMyGuest/Views/Guests/Index.cshtml
@{
    Layout = "_Layout";
}

@using BeMyGuest.Models
@model IEnumerable<BeMyGuest.Models.Guest>;

<h2>Guest List</h2>
<hr>
@if (Model.Any())
{
    <ul style="list-style: none;">
        @foreach(Guest guest in Model)
        {
            <div class="card" style="width: 36rem;">
                <div class="card-body">
                    <li>@Html.ActionLink($"{guest.Name}", "Details", new { id = guest.GuestId })</li>
                    <li>High Risk Attendee: @guest.HighRisk</li>
                    <li>Has Completed Questionnaire: @guest.CompletedQuestionnaire</li>
                </div>
            </div>
        }
    </ul>
}
else
{
    <div class="card" style="width: 36rem;">
        <div class="card-body">
            <h3>There are no guests added yet.</h3>
        </div>
    </div>
}
<h3>@Html.ActionLink("Add a New Guest", "Create") || @Html.ActionLink("Back to Home", "Index", "Home")</h3>

BeMyGuest/Views/Guests/SocialQs.cshtml
@{
    Layout = "_Layout";
}
<h1>Social Q's</h1>
<h2>Social Questions for your Social Cues</h2>
<h3>Please fill this form out to communicate with guests any information you may feel uncomfortable talking about in
    person but should have guests be aware of.</h3>
<h4>The purpose of this form is to promote communication, awareness, diversity and equality. </h4>
<h5>Make socially awkward, socially awesome!</h5>

<div class="form-group">
    <p>1. What are your pronouns?</p>
    <input type="text">
</div>
<div class="form-group">
    <p>2. Did you complete the COVID Questionnaire?</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
</div>
<div class="form-group">
    <p>3. Did you complete the COVID Questionnaire?</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
</div>
<div class="form-group">
    <p>4. Do you have any condtions that put you at a high risk?</p>
    <p>Examples: pregnant, medical condition, immune deficiency</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
    <p>Explanation:</p>
    <input type="text">
</div>
<div class="form-group">
    <p>5. Do you have any condtions that you would like the host/party to be aware of?</p>
    <p>Examples: diabetic, dementia, blind, deaf</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
    <p>Explanation:</p>
    <input type="text">
</div>
<div class="form-group">
    <p>6. Have you recently traveled?</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
</div>
<div class="form-group">
    <p>7. Do you have any medical mobility needs?</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
    <p>If yes, please explain what the host should provide: (Example: wheel chair accessibility)</p>
    <input type="text">
</div>
<div class="form-group">
    <p>8. Do you have a service animal?</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
    <p>Instructions: (Example: Please do not pet service animal)</p>
    <input type="text">
</div>
<div class="form-group">
    <p>9. Do you have any dietary restrictions?</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
    <p>Explanation</p>
    <input type="text">
</div>
<div class="form-group">
    <p>10. Do you have any allergies?</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
    <p>Explanation</p>
    <input type="text">
</div>
<div class="form-group">
    <p>11. Preferred language?</p>
    <input type="text">
    <p>Would you like to be provided with a translator?</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
</div>
<div class="form-group">
    <p>12. Alcohol-free or friendly?</p>
    <input type="radio"> Alcohol-free <br>
    <input type="radio"> Alcohol-friendly <br>
</div>
<div class="form-group">
    <p>13. Do you prefer no physical contact?</p>
    <p>Example: Not a hugger, no handshakes, elbow bumps only</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
    <p>Explanation</p>
    <input type="text">
</div>
<div class="form-group">
    <p>14. Do you have a plus one?</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
    <p>Please have your plus one fill out the COVID Questionnaire and Social Q's form</p>
</div>
<div class="form-group">
    <p>15. Will you be bringing small children?</p>
    <p>Example: Not a hugger, no handshakes, elbow bumps only</p>
    <input type="radio"> Yes <br>
    <input type="radio"> No <br>
    <p>Please provide any special needs the children may need.</p>
    <p>Example: high chair, booster seat, changing area, kids menu</p>
    <input type="text">
</div>
<div class="form-group">
    <input type="submit" value="Submit" class="btn btn-default" />
</div>